# RF

In [160]:
"""BreastCancerAI (c) by Roi Dvir
BreastCancerAI is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.
You should have received a copy of the license along with this work. If not, see <http://creativecommons.org/licenses/by-nc-nd/4.0/>."""


# import libraries
import numpy as np
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
from matplotlib import rcParams
from matplotlib.cm import rainbow
%matplotlib inline
import statsmodels.api as sm
import scipy.stats as st
import warnings
warnings.filterwarnings('ignore')

In [161]:
# Sklearn library for implementing Machine Learning models and processing of data
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.utils import shuffle
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_selection import RFE
from sklearn.model_selection import cross_val_score

In [162]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [163]:
#importing the dataset
dataset = pd.read_csv('./data/Breast_Cancer_Data_CSV.csv')
dataset.drop(['ID number'],axis=1,inplace=True)
dataset.head()
print("Cancer data set dimensions : {}".format(dataset.shape))
dataset.head()

Cancer data set dimensions : (569, 31)


radius.mean  texture.mean  perimeter.mean  area.mean  smoothness.mean  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   compactness.mean  concavity.mean  concave points.mean  symmetry.mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   fractal dimension    ...      texture.w  perimeter.w  area.w  smoothness.w  \
0            0.07871    ...          17.33       184.60  2019.0        0.1622   
1            0.05667    ...          23.41       158.80  1956.0        0.1238   
2            0.05999    ...          25.53       152.50  1709.0        0.1444   
3            0.09744    ...          26.50        98.87   567.7        0.2098   
4            0.05883    ...          16.67       152.20  1575.0        0.1374   

   compactness.w  concavity.w  concave points.w  symmetry.w  \
0         0.6656       0.7119            0.2654      0.4601   
1         0.1866       0.2416            0.1860      0.2750   
2         0.4245       0.4504            0.2430      0.3613   
3         0.8663       0.6869            0.2575      0.6638   
4         0.2050       0.4000            0.1625      0.2364   

   fractal dimension.w  Diagnosis  
0              0.11890          M  
1              0.08902          M  
2              0.08758          M  
3              0.17300          M  
4              0.07678          M  

[5 rows x 31 columns]

In [164]:
dataset.head()

radius.mean  texture.mean  perimeter.mean  area.mean  smoothness.mean  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   compactness.mean  concavity.mean  concave points.mean  symmetry.mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   fractal dimension    ...      texture.w  perimeter.w  area.w  smoothness.w  \
0            0.07871    ...          17.33       184.60  2019.0        0.1622   
1            0.05667    ...          23.41       158.80  1956.0        0.1238   
2            0.05999    ...          25.53       152.50  1709.0        0.1444   
3            0.09744    ...          26.50        98.87   567.7        0.2098   
4            0.05883    ...          16.67       152.20  1575.0        0.1374   

   compactness.w  concavity.w  concave points.w  symmetry.w  \
0         0.6656       0.7119            0.2654      0.4601   
1         0.1866       0.2416            0.1860      0.2750   
2         0.4245       0.4504            0.2430      0.3613   
3         0.8663       0.6869            0.2575      0.6638   
4         0.2050       0.4000            0.1625      0.2364   

   fractal dimension.w  Diagnosis  
0              0.11890          M  
1              0.08902          M  
2              0.08758          M  
3              0.17300          M  
4              0.07678          M  

[5 rows x 31 columns]

In [165]:
#features list

In [166]:
# select features
features=list(dataset.columns[[23, 20, 22, 27, 7, 2, 0, 13, 3, 24]])

features.append(dataset.columns[-1])
dataset = dataset[features]

In [167]:
dataset

area.w  radius.w  perimeter.w  concave points.w  concave points.mean  \
0    2019.0    25.380       184.60           0.26540             0.147100   
1    1956.0    24.990       158.80           0.18600             0.070170   
2    1709.0    23.570       152.50           0.24300             0.127900   
3     567.7    14.910        98.87           0.25750             0.105200   
4    1575.0    22.540       152.20           0.16250             0.104300   
5     741.6    15.470       103.40           0.17410             0.080890   
6    1606.0    22.880       153.20           0.19320             0.074000   
7     897.0    17.060       110.60           0.15560             0.059850   
8     739.3    15.490       106.20           0.20600             0.093530   
9     711.4    15.090        97.65           0.22100             0.085430   
10   1150.0    19.190       123.80           0.09975             0.033230   
11   1299.0    20.420       136.50           0.18100             0.066060   
12   1332.0    20.960       151.70           0.17670             0.111800   
13    876.5    16.840       112.00           0.11190             0.053640   
14    697.7    15.030       108.80           0.22080             0.080250   
15    943.2    17.460       124.10           0.17120             0.073640   
16   1138.0    19.070       123.40           0.16090             0.052590   
17   1315.0    20.960       136.80           0.20730             0.102800   
18   2398.0    27.320       186.80           0.23880             0.094980   
19    711.2    15.110        99.70           0.12880             0.047810   
20    630.5    14.500        96.09           0.07283             0.031100   
21    314.9    10.230        65.13           0.06227             0.020760   
22    980.9    18.070       125.10           0.23930             0.097560   
23   2615.0    29.170       188.00           0.20090             0.086320   
24   2215.0    26.460       177.00           0.20950             0.091700   
25   1461.0    22.250       152.40           0.25500             0.140100   
26    896.9    17.620       122.40           0.27010             0.087830   
27   1403.0    21.310       139.90           0.14900             0.077310   
28   1269.0    20.270       149.30           0.20240             0.087510   
29   1227.0    20.010       134.90           0.14560             0.079530   
..      ...       ...          ...               ...                  ...   
539   223.6     8.678        54.49           0.05000             0.013640   
540   457.8    12.260        78.78           0.06918             0.025940   
541   808.9    16.220       113.50           0.12050             0.038900   
542   826.4    16.510       107.40           0.10950             0.030270   
543   629.6    14.370        92.48           0.07958             0.032750   
544   688.6    15.050        99.17           0.06845             0.023690   
545   729.8    15.350        97.58           0.07174             0.024430   
546   384.9    11.250        71.12           0.02381             0.005495   
547   357.4    10.830        71.08           0.08333             0.024380   
548   364.2    10.930        69.10           0.03846             0.009615   
549   505.6    13.030        83.90           0.03264             0.008160   
550   412.3    11.660        74.08           0.00000             0.000000   
551   436.6    12.020        77.80           0.06413             0.022570   
552   594.7    13.870        88.10           0.06498             0.014990   
553   295.8     9.845        62.86           0.02564             0.012820   
554   595.7    13.890        88.84           0.06493             0.023430   
555   357.6    10.840        69.57           0.09127             0.027380   
556   347.3    10.650        67.88           0.02232             0.011160   
557   330.6    10.490        66.50           0.00000             0.000000   
558   733.5    15.480       105.90           0.11050             0.037360   
5

In [168]:
def find_features_importance(n):
    clf = RandomForestClassifier(n_estimators=100, max_features=10)
    clf = clf.fit(X_train, y_train)
    importances = clf.feature_importances_
    idx = (-importances).argsort()[:n]
    return( idx )

In [169]:
# split dataframe into two based on diagnosis
dfM=dataset[dataset['Diagnosis'] ==1]
dfB=dataset[dataset['Diagnosis'] ==0]
dataset1 = shuffle(dataset)
X = dataset1.iloc[:, :-1].values
Y = dataset1.iloc[:, -1].values
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)
#Encoding categorical data values 
# split our dataset into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size =     0.3, random_state = 0)
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [170]:
find_features_importance(10)

array([2, 3, 0, 1, 4, 9, 7, 8, 6, 5])

In [171]:
def values_confusion_matrix(y_test,y_pred):
    cm=confusion_matrix(y_test,y_pred)
    conf_matrix=pd.DataFrame(data=cm,columns=['Predicted:0','Predicted:1'],index=['Actual:0','Actual:1'])
    TN=cm[0,0]
    TP=cm[1,1]
    FN=cm[1,0]
    FP=cm[0,1]
    Accuracy=round((TN+TP)/float(TN+TP+FN+FP),3)
    Misclassification=1-Accuracy
    Sensitivity=round(TP/(float(TP+FN)),3)
    Specifity=round(TN/(float(TN+cm[0,1])),3)
    not_detected=round(FN/(FN+TN),5)
    a=np.array([Accuracy,Sensitivity,Specifity, not_detected])
    return(a)

In [172]:
def draw_confusion_matrix(y_test,y_pred):
    cm=confusion_matrix(y_test,y_pred)
    conf_matrix=pd.DataFrame(data=cm,columns=['Predicted:0','Predicted:1'],index=['Actual:0','Actual:1'])
    TN=cm[0,0]
    TP=cm[1,1]
    FN=cm[1,0]
    FP=cm[0,1]
    Accuracy=round((TN+TP)/float(TN+TP+FN+FP),3)
    Misclassification=1-Accuracy
    Sensitivity=round(TP/(float(TP+FN)),3)
    Specifity=round(TN/(float(TN+cm[0,1])),3)
    not_detected=round(FN/(FN+TN),5)
    print ('Accuracy=',Accuracy,'Sensitivity=', Sensitivity, 'Specifity=' ,Specifity,' notdetected=' , not_detected)
    plt.figure(figsize = (8,5))
    sn.heatmap(conf_matrix, annot=True,fmt='d',cmap="YlGnBu")

In [173]:
def rf_model():
    rf_classifier = RandomForestClassifier(n_estimators=100, max_features=10)
    rf=rf_classifier
    rf.fit(X_train, y_train)
    y_pred=rf.predict(X_test)
    print("score=",rf.score(X_test, y_test) )
    draw_confusion_matrix(y_test,y_pred)

In [174]:
def rf_model_1():
    rf_classifier = RandomForestClassifier(n_estimators=100, max_features=10)
    rf=rf_classifier
    rf.fit(X_train, y_train)
    y_pred=rf.predict(X_test)
    return(y_pred)

In [175]:
def rf_model_2():
    rf_classifier = RandomForestClassifier(n_estimators=100, max_features=10)
    rf=rf_classifier
    rf.fit(X_train, y_train)
    y_pred=rf.predict_proba(X_test)
    return( y_pred)

In [176]:
rf_model_2()

array([[1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.98, 0.02],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.1 , 0.9 ],
       [0.  , 1.  ],
       [0.94, 0.06],
       [0.42, 0.58],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.93, 0.07],
       [0.  , 1.  ],
       [0.99, 0.01],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.78, 0.22],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.06, 0.94],
       [0.  , 1.  ],
       [0.83, 0.17],
       [1.  , 0.  ],
       [0.91, 0.09],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.9 , 0.1 ],
       [0.02, 0.98],
       [1.  ,

In [177]:
def cross_valid_score(n):
    clf =  RandomForestClassifier(n_estimators=100, max_features=10)
    scores = cross_val_score(clf, X, Y, cv=n)
    print('average=',np.average(scores),'std=', np.std(scores))

In [178]:
cross_valid_score(5)

average= 0.9437322046941132 std= 0.017422629244133223


In [179]:
para=np.zeros([1000,4])
i=0
for i in range (1000):
    dataset1 = shuffle(dataset)
    X = dataset1.iloc[:, :-1].values
    Y = dataset1.iloc[:, -1].values
    labelencoder_Y = LabelEncoder()
    Y = labelencoder_Y.fit_transform(Y)
    #Encoding categorical data values 
    # split our dataset into training and testing datasets
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size =     0.3,     random_state = 0)
    scaler = StandardScaler().fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)
    y_pred=rf_model_1()
    a=values_confusion_matrix(y_test,y_pred)
    para[i,:]=a
    i=i+1

print(np.average(para, axis=0))
print(np.std(para, axis=0))

[0.94058  0.913552 0.956707 0.050902]
[0.01570241 0.03517626 0.02044185 0.02074324]
